//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Day1.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Day1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2010
        ///1856
        ///1905
        ///1786
        ///1557
        ///1995
        ///1830
        ///1971
        ///1909
        ///1500
        ///1806
        ///1846
        ///2003
        ///1839
        ///1943
        ///1977
        ///1537
        ///689
        ///1861
        ///1886
        ///1815
        ///1763
        ///1834
        ///1881
        ///1952
        ///1853
        ///1775
        ///1835
        ///1874
        ///1948
        ///1978
        ///347
        ///1672
        ///885
        ///1709
        ///1826
        ///1911
        ///1644
        ///1064
        ///1561
        ///1966
        ///1352
        ///1347
        ///1928
        ///1756
        ///615
        ///1513
        ///1932
        ///1968
        ///1762
        ///1842
        ///1475
        ///1921
        ///1716
        ///1533
        ///1975
        ///1924
        ///1850
        ///1456
        ///1783
        ///1587
        ///1913
        ///1908
        ///1502
        ///1993
        ///1635
        ///1691
        ///1706
        ///1871
        ///1857
        ///1915
        ///1604
        ///1618
        ///1902
        ///1860
        ///1648
        ///1933
        ///1999
        ///1960
        ///1389
        ///1858
        ///1793
        ///1609
        ///1484
        ///1735
        ///1535
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
    }
}
